Traceback (most recent call last):
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import math
from handcalcs.decorator import handcalc
import forallpeople as si 
si.environment('default')
si.environment()
@handcalc(override='long', jupyter_display=True)
def calc( pi , E_modul, I_y ,  L):
    
    sigma_kr = pi ** 2 * E_modul * I_y / ( L ** 2 ) 
    
    
    return sigma_kr
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [1], line 2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmath[39;00m
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhandcalcs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdecorator[39;00m [38;5;28;01mimport[39;00m handcalc
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mforallpeople[39;00m [38;5;28;01mas[39;00m [38;5;21;01msi[39;00m 
[0;32m      4[0m si[38;5;241m.[39menvironment([38;5;124m'[39m[38;5;124mdefault[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'handcalcs'
ModuleNotFoundError: No module named 'handcalcs'

